# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dataPlotWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(941, 672)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(60, 50))
        self.label.setMaximumSize(QtCore.QSize(80, 50))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_currentChoose = QtWidgets.QLabel(Form)
        self.label_currentChoose.setMinimumSize(QtCore.QSize(40, 50))
        self.label_currentChoose.setMaximumSize(QtCore.QSize(40, 50))
        self.label_currentChoose.setText("")
        self.label_currentChoose.setObjectName("label_currentChoose")
        self.horizontalLayout_5.addWidget(self.label_currentChoose)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_singlechannel = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_singlechannel.setObjectName("comboBox_singlechannel")
        self.horizontalLayout.addWidget(self.comboBox_singlechannel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.radioButton_singlechannel_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_singlechannel_1.setChecked(True)
        self.radioButton_singlechannel_1.setObjectName("radioButton_singlechannel_1")
        self.verticalLayout.addWidget(self.radioButton_singlechannel_1)
        self.radioButton_singlechannel_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_singlechannel_2.setObjectName("radioButton_singlechannel_2")
        self.verticalLayout.addWidget(self.radioButton_singlechannel_2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_coincidentChannel = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_coincidentChannel.setObjectName("comboBox_coincidentChannel")
        self.horizontalLayout_2.addWidget(self.comboBox_coincidentChannel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_coincidentChannel1_1 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_coincidentChannel1_1.setChecked(True)
        self.radioButton_coincidentChannel1_1.setObjectName("radioButton_coincidentChannel1_1")
        self.verticalLayout_2.addWidget(self.radioButton_coincidentChannel1_1)
        self.radioButton_coincidentChannel1_2 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_coincidentChannel1_2.setObjectName("radioButton_coincidentChannel1_2")
        self.verticalLayout_2.addWidget(self.radioButton_coincidentChannel1_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_coincidentChannel2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_coincidentChannel2.setObjectName("comboBox_coincidentChannel2")
        self.horizontalLayout_3.addWidget(self.comboBox_coincidentChannel2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_coincidentChannel2_1 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_coincidentChannel2_1.setChecked(True)
        self.radioButton_coincidentChannel2_1.setObjectName("radioButton_coincidentChannel2_1")
        self.verticalLayout_3.addWidget(self.radioButton_coincidentChannel2_1)
        self.radioButton_coincidentChannel2_2 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_coincidentChannel2_2.setObjectName("radioButton_coincidentChannel2_2")
        self.verticalLayout_3.addWidget(self.radioButton_coincidentChannel2_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_allCount = QtWidgets.QLabel(self.groupBox_3)
        self.label_allCount.setText("")
        self.label_allCount.setObjectName("label_allCount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_allCount)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_triggerCount = QtWidgets.QLabel(self.groupBox_3)
        self.label_triggerCount.setText("")
        self.label_triggerCount.setObjectName("label_triggerCount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_triggerCount)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_coincidentCount = QtWidgets.QLabel(self.groupBox_3)
        self.label_coincidentCount.setText("")
        self.label_coincidentCount.setObjectName("label_coincidentCount")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_coincidentCount)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.widget = currentEnergeCount(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_save.setText(_translate("Form", "保存"))
        self.label.setText(_translate("Form", "当前选择："))
        self.groupBox.setTitle(_translate("Form", "能谱"))
        self.label_3.setText(_translate("Form", "选择通道："))
        self.radioButton_singlechannel_1.setText(_translate("Form", "高增益"))
        self.radioButton_singlechannel_2.setText(_translate("Form", "低增益"))
        self.groupBox_2.setTitle(_translate("Form", "双通道符合"))
        self.label_4.setText(_translate("Form", "选择通道1："))
        self.radioButton_coincidentChannel1_1.setText(_translate("Form", "高增益"))
        self.radioButton_coincidentChannel1_2.setText(_translate("Form", "低增益"))
        self.label_5.setText(_translate("Form", "选择通道2："))
        self.radioButton_coincidentChannel2_1.setText(_translate("Form", "高增益"))
        self.radioButton_coincidentChannel2_2.setText(_translate("Form", "低增益"))
        self.groupBox_3.setTitle(_translate("Form", "计数"))
        self.label_2.setText(_translate("Form", "总计数："))
        self.label_7.setText(_translate("Form", "触发计数："))
        self.label_8.setText(_translate("Form", "符合计数："))

from myWidget import currentEnergeCount
