# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GL3D.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 743)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_GL = GLViewWidget(Form)
        self.widget_GL.setObjectName("widget_GL")
        self.horizontalLayout_2.addWidget(self.widget_GL)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_colorMap = GradientWidget(Form)
        self.widget_colorMap.setMaximumSize(QtCore.QSize(220, 16777215))
        self.widget_colorMap.setObjectName("widget_colorMap")
        self.horizontalLayout.addWidget(self.widget_colorMap)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(110, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.doubleSpinBox_maxAngle = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_maxAngle.setMaximum(90.0)
        self.doubleSpinBox_maxAngle.setProperty("value", 30.0)
        self.doubleSpinBox_maxAngle.setObjectName("doubleSpinBox_maxAngle")
        self.verticalLayout.addWidget(self.doubleSpinBox_maxAngle)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.doubleSpinBox_minAngle = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_minAngle.setProperty("value", 10.0)
        self.doubleSpinBox_minAngle.setObjectName("doubleSpinBox_minAngle")
        self.verticalLayout.addWidget(self.doubleSpinBox_minAngle)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMaximumSize(QtCore.QSize(110, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.doubleSpinBox_maxZ = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_maxZ.setMaximum(1500.0)
        self.doubleSpinBox_maxZ.setProperty("value", 850.0)
        self.doubleSpinBox_maxZ.setObjectName("doubleSpinBox_maxZ")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_maxZ)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.doubleSpinBox_minZ = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_minZ.setMaximum(1500.0)
        self.doubleSpinBox_minZ.setProperty("value", 600.0)
        self.doubleSpinBox_minZ.setObjectName("doubleSpinBox_minZ")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_minZ)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setMaximumSize(QtCore.QSize(110, 200))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.lineEdit_readyRatio = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_readyRatio.setEnabled(False)
        self.lineEdit_readyRatio.setObjectName("lineEdit_readyRatio")
        self.verticalLayout_8.addWidget(self.lineEdit_readyRatio)
        self.pushButton_addRatioPos = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_addRatioPos.setObjectName("pushButton_addRatioPos")
        self.verticalLayout_8.addWidget(self.pushButton_addRatioPos)
        self.pushButton_clearRatioPos = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_clearRatioPos.setObjectName("pushButton_clearRatioPos")
        self.verticalLayout_8.addWidget(self.pushButton_clearRatioPos)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMaximumSize(QtCore.QSize(110, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_showPoca = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_showPoca.setChecked(True)
        self.checkBox_showPoca.setObjectName("checkBox_showPoca")
        self.verticalLayout_7.addWidget(self.checkBox_showPoca)
        self.checkBox_Ratio = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Ratio.setObjectName("checkBox_Ratio")
        self.verticalLayout_7.addWidget(self.checkBox_Ratio)
        self.checkBox_showModel = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_showModel.setChecked(True)
        self.checkBox_showModel.setObjectName("checkBox_showModel")
        self.verticalLayout_7.addWidget(self.checkBox_showModel)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "-max"))
        self.label_6.setText(_translate("Form", "-60%"))
        self.label_7.setText(_translate("Form", "-40%"))
        self.label_8.setText(_translate("Form", "-20%"))
        self.label_9.setText(_translate("Form", "-0°"))
        self.groupBox.setTitle(_translate("Form", "angle filer"))
        self.label.setText(_translate("Form", "max angle:"))
        self.doubleSpinBox_maxAngle.setSuffix(_translate("Form", "°"))
        self.label_2.setText(_translate("Form", "min angle:"))
        self.doubleSpinBox_minAngle.setSuffix(_translate("Form", "°"))
        self.groupBox_2.setTitle(_translate("Form", "z axis filer"))
        self.label_3.setText(_translate("Form", "max z:"))
        self.doubleSpinBox_maxZ.setSuffix(_translate("Form", "mm"))
        self.label_4.setText(_translate("Form", "min z:"))
        self.doubleSpinBox_minZ.setSuffix(_translate("Form", "mm"))
        self.groupBox_4.setTitle(_translate("Form", "ratio"))
        self.label_10.setText(_translate("Form", "ready pos"))
        self.pushButton_addRatioPos.setText(_translate("Form", "add pos"))
        self.pushButton_clearRatioPos.setText(_translate("Form", "clear"))
        self.groupBox_3.setTitle(_translate("Form", "display "))
        self.checkBox_showPoca.setText(_translate("Form", "poca"))
        self.checkBox_Ratio.setText(_translate("Form", "ratio"))
        self.checkBox_showModel.setText(_translate("Form", "model"))

from pyqtgraph import GradientWidget
from pyqtgraph.opengl import GLViewWidget
