# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout_3.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_toolBox = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_toolBox.setMaximumSize(QtCore.QSize(300, 524287))
        self.dockWidget_toolBox.setObjectName("dockWidget_toolBox")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBox.setObjectName("toolBox")
        self.page_linkBehave = QtWidgets.QWidget()
        self.page_linkBehave.setGeometry(QtCore.QRect(0, 0, 272, 207))
        self.page_linkBehave.setObjectName("page_linkBehave")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_linkBehave)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_configFile = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_configFile.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_configFile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_configFile.setObjectName("comboBox_configFile")
        self.horizontalLayout.addWidget(self.comboBox_configFile)
        self.pushButton_config = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_config.setMinimumSize(QtCore.QSize(60, 28))
        self.pushButton_config.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_config.setObjectName("pushButton_config")
        self.horizontalLayout.addWidget(self.pushButton_config)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_sendCommand = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_sendCommand.setObjectName("lineEdit_sendCommand")
        self.horizontalLayout_2.addWidget(self.lineEdit_sendCommand)
        self.pushButton_sendCommand = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_sendCommand.setMinimumSize(QtCore.QSize(60, 28))
        self.pushButton_sendCommand.setMaximumSize(QtCore.QSize(60, 28))
        self.pushButton_sendCommand.setObjectName("pushButton_sendCommand")
        self.horizontalLayout_2.addWidget(self.pushButton_sendCommand)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcdNumber_h_m = QtWidgets.QLCDNumber(self.page_linkBehave)
        self.lcdNumber_h_m.setMinimumSize(QtCore.QSize(0, 0))
        self.lcdNumber_h_m.setDigitCount(5)
        self.lcdNumber_h_m.setObjectName("lcdNumber_h_m")
        self.horizontalLayout_3.addWidget(self.lcdNumber_h_m)
        self.lcdNumber_s_ms = QtWidgets.QLCDNumber(self.page_linkBehave)
        self.lcdNumber_s_ms.setObjectName("lcdNumber_s_ms")
        self.horizontalLayout_3.addWidget(self.lcdNumber_s_ms)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_dataReceive = QtWidgets.QPushButton(self.page_linkBehave)
        self.pushButton_dataReceive.setCheckable(True)
        self.pushButton_dataReceive.setObjectName("pushButton_dataReceive")
        self.horizontalLayout_3.addWidget(self.pushButton_dataReceive)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolBox.addItem(self.page_linkBehave, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 300, 329))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_singal_tier = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_singal_tier.setObjectName("comboBox_singal_tier")
        self.horizontalLayout_5.addWidget(self.comboBox_singal_tier)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_singal_channel = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_singal_channel.setObjectName("comboBox_singal_channel")
        self.horizontalLayout_6.addWidget(self.comboBox_singal_channel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinBox_baseLine = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_baseLine.setMaximum(4095)
        self.spinBox_baseLine.setObjectName("spinBox_baseLine")
        self.horizontalLayout_7.addWidget(self.spinBox_baseLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_singal = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_singal.setObjectName("checkBox_singal")
        self.horizontalLayout_4.addWidget(self.checkBox_singal)
        self.pushButton_singal_addPlot = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_singal_addPlot.setObjectName("pushButton_singal_addPlot")
        self.horizontalLayout_4.addWidget(self.pushButton_singal_addPlot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget_toolBox.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_toolBox)
        self.dockWidget_messageQueue = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_messageQueue.setObjectName("dockWidget_messageQueue")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_messageQueue = QtWidgets.QTextBrowser(self.dockWidgetContents_2)
        self.textBrowser_messageQueue.setObjectName("textBrowser_messageQueue")
        self.verticalLayout_2.addWidget(self.textBrowser_messageQueue)
        self.dockWidget_messageQueue.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_messageQueue)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LUMIS实时能谱"))
        self.dockWidget_toolBox.setWindowTitle(_translate("MainWindow", "工具箱"))
        self.groupBox.setTitle(_translate("MainWindow", "选择配置模式"))
        self.pushButton_config.setText(_translate("MainWindow", "配置"))
        self.groupBox_2.setTitle(_translate("MainWindow", "手动发送命令"))
        self.pushButton_sendCommand.setText(_translate("MainWindow", "发送"))
        self.pushButton_dataReceive.setText(_translate("MainWindow", "开始接收数据"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_linkBehave), _translate("MainWindow", "连接操作"))
        self.groupBox_3.setTitle(_translate("MainWindow", "能谱显示"))
        self.label.setText(_translate("MainWindow", "所在层："))
        self.label_2.setText(_translate("MainWindow", "所选通道："))
        self.label_3.setText(_translate("MainWindow", "基线设置："))
        self.checkBox_singal.setText(_translate("MainWindow", "高增益"))
        self.pushButton_singal_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "图像显示"))
        self.dockWidget_messageQueue.setWindowTitle(_translate("MainWindow", "消息队列"))

