# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.dockArea = DockArea(self.centralwidget)
        self.dockArea.setObjectName("dockArea")
        self.horizontalLayout_16.addWidget(self.dockArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_toolBox = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_toolBox.setMaximumSize(QtCore.QSize(450, 524287))
        self.dockWidget_toolBox.setObjectName("dockWidget_toolBox")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBox.setObjectName("toolBox")
        self.page_linkBehave = QtWidgets.QWidget()
        self.page_linkBehave.setGeometry(QtCore.QRect(0, -4, 293, 335))
        self.page_linkBehave.setObjectName("page_linkBehave")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_linkBehave)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_clockSynchronization = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_clockSynchronization.setObjectName("pushButton_clockSynchronization")
        self.horizontalLayout_17.addWidget(self.pushButton_clockSynchronization)
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_17.addWidget(self.pushButton_reset)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_configFile = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_configFile.setMinimumSize(QtCore.QSize(0, 21))
        self.comboBox_configFile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_configFile.setObjectName("comboBox_configFile")
        self.horizontalLayout.addWidget(self.comboBox_configFile)
        self.pushButton_config = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_config.setMinimumSize(QtCore.QSize(60, 28))
        self.pushButton_config.setMaximumSize(QtCore.QSize(60, 30))
        self.pushButton_config.setObjectName("pushButton_config")
        self.horizontalLayout.addWidget(self.pushButton_config)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_sendCommand = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_sendCommand.setObjectName("lineEdit_sendCommand")
        self.horizontalLayout_2.addWidget(self.lineEdit_sendCommand)
        self.pushButton_sendCommand = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_sendCommand.setMinimumSize(QtCore.QSize(60, 28))
        self.pushButton_sendCommand.setMaximumSize(QtCore.QSize(60, 28))
        self.pushButton_sendCommand.setObjectName("pushButton_sendCommand")
        self.horizontalLayout_2.addWidget(self.pushButton_sendCommand)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcdNumber_h_m = QtWidgets.QLCDNumber(self.page_linkBehave)
        self.lcdNumber_h_m.setMinimumSize(QtCore.QSize(0, 0))
        self.lcdNumber_h_m.setDigitCount(5)
        self.lcdNumber_h_m.setObjectName("lcdNumber_h_m")
        self.horizontalLayout_3.addWidget(self.lcdNumber_h_m)
        self.lcdNumber_s_ms = QtWidgets.QLCDNumber(self.page_linkBehave)
        self.lcdNumber_s_ms.setObjectName("lcdNumber_s_ms")
        self.horizontalLayout_3.addWidget(self.lcdNumber_s_ms)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_dataReceive = QtWidgets.QPushButton(self.page_linkBehave)
        self.pushButton_dataReceive.setCheckable(True)
        self.pushButton_dataReceive.setObjectName("pushButton_dataReceive")
        self.horizontalLayout_3.addWidget(self.pushButton_dataReceive)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_linkBehave)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.spinBox_timer_hour = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_timer_hour.setObjectName("spinBox_timer_hour")
        self.horizontalLayout_13.addWidget(self.spinBox_timer_hour)
        self.spinBox_timer_minute = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_timer_minute.setMaximum(59)
        self.spinBox_timer_minute.setObjectName("spinBox_timer_minute")
        self.horizontalLayout_13.addWidget(self.spinBox_timer_minute)
        self.checkBox_timer = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_timer.setObjectName("checkBox_timer")
        self.horizontalLayout_13.addWidget(self.checkBox_timer)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.toolBox.addItem(self.page_linkBehave, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 279, 440))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_singal_tier = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_singal_tier.setObjectName("comboBox_singal_tier")
        self.horizontalLayout_5.addWidget(self.comboBox_singal_tier)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_singal_channel = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_singal_channel.setObjectName("comboBox_singal_channel")
        self.horizontalLayout_6.addWidget(self.comboBox_singal_channel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinBox_baseLine = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_baseLine.setMinimum(0)
        self.spinBox_baseLine.setMaximum(4095)
        self.spinBox_baseLine.setProperty("value", 415)
        self.spinBox_baseLine.setObjectName("spinBox_baseLine")
        self.horizontalLayout_7.addWidget(self.spinBox_baseLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_singal_addPlot = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_singal_addPlot.setObjectName("pushButton_singal_addPlot")
        self.horizontalLayout_4.addWidget(self.pushButton_singal_addPlot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.comboBox_coincidence_tier = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_coincidence_tier.setObjectName("comboBox_coincidence_tier")
        self.horizontalLayout_8.addWidget(self.comboBox_coincidence_tier)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.comboBox_coincidence_showChannel = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_coincidence_showChannel.setObjectName("comboBox_coincidence_showChannel")
        self.horizontalLayout_9.addWidget(self.comboBox_coincidence_showChannel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.comboBox_coincidence_coinChannel = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_coincidence_coinChannel.setObjectName("comboBox_coincidence_coinChannel")
        self.horizontalLayout_10.addWidget(self.comboBox_coincidence_coinChannel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.spinBox_coincidence_baseline = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_coincidence_baseline.setMaximum(4025)
        self.spinBox_coincidence_baseline.setProperty("value", 415)
        self.spinBox_coincidence_baseline.setObjectName("spinBox_coincidence_baseline")
        self.horizontalLayout_12.addWidget(self.spinBox_coincidence_baseline)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.pushButton_coincidence_addPlot = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_coincidence_addPlot.setObjectName("pushButton_coincidence_addPlot")
        self.horizontalLayout_11.addWidget(self.pushButton_coincidence_addPlot)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.comboBox_oneLayerChannel_tier = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_oneLayerChannel_tier.setObjectName("comboBox_oneLayerChannel_tier")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.comboBox_oneLayerChannel_tier.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_oneLayerChannel_tier)
        self.pushButton_oneLayerChannel_addPlot = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_oneLayerChannel_addPlot.setObjectName("pushButton_oneLayerChannel_addPlot")
        self.horizontalLayout_14.addWidget(self.pushButton_oneLayerChannel_addPlot)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.toolBox.addItem(self.page_2, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 300, 331))
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.pushButton_triggerCondition_addPlot = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_triggerCondition_addPlot.setObjectName("pushButton_triggerCondition_addPlot")
        self.horizontalLayout_15.addWidget(self.pushButton_triggerCondition_addPlot)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.pushButton_XYTriggerCondition_addPlot = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_XYTriggerCondition_addPlot.setObjectName("pushButton_XYTriggerCondition_addPlot")
        self.horizontalLayout_18.addWidget(self.pushButton_XYTriggerCondition_addPlot)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.pushButton_threeD_addPlot = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_threeD_addPlot.setObjectName("pushButton_threeD_addPlot")
        self.horizontalLayout_19.addWidget(self.pushButton_threeD_addPlot)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 195, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.toolBox.addItem(self.page, "")
        self.page_alarm = QtWidgets.QWidget()
        self.page_alarm.setGeometry(QtCore.QRect(0, 0, 300, 331))
        self.page_alarm.setObjectName("page_alarm")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_alarm)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_alarm)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_alarm_messageBox = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_alarm_messageBox.setChecked(False)
        self.checkBox_alarm_messageBox.setObjectName("checkBox_alarm_messageBox")
        self.horizontalLayout_20.addWidget(self.checkBox_alarm_messageBox)
        self.pushButton_alarm_clear = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_alarm_clear.setObjectName("pushButton_alarm_clear")
        self.horizontalLayout_20.addWidget(self.pushButton_alarm_clear)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.verticalLayout_11.addWidget(self.groupBox_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.toolBox.addItem(self.page_alarm, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget_toolBox.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_toolBox)
        self.dockWidget_messageQueue = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_messageQueue.setObjectName("dockWidget_messageQueue")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_messageQueue = QtWidgets.QTextBrowser(self.dockWidgetContents_2)
        self.textBrowser_messageQueue.setObjectName("textBrowser_messageQueue")
        self.verticalLayout_2.addWidget(self.textBrowser_messageQueue)
        self.dockWidget_messageQueue.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_messageQueue)
        self.action_baseline_importFromData = QtWidgets.QAction(MainWindow)
        self.action_baseline_importFromData.setObjectName("action_baseline_importFromData")
        self.action_baseline_changeBaseline = QtWidgets.QAction(MainWindow)
        self.action_baseline_changeBaseline.setObjectName("action_baseline_changeBaseline")
        self.action_configuration = QtWidgets.QAction(MainWindow)
        self.action_configuration.setObjectName("action_configuration")
        self.action_baseline_measureBaseline = QtWidgets.QAction(MainWindow)
        self.action_baseline_measureBaseline.setObjectName("action_baseline_measureBaseline")
        self.action_dataPlayBack = QtWidgets.QAction(MainWindow)
        self.action_dataPlayBack.setObjectName("action_dataPlayBack")
        self.action_offlineDataShow = QtWidgets.QAction(MainWindow)
        self.action_offlineDataShow.setObjectName("action_offlineDataShow")
        self.menu_2.addAction(self.action_baseline_importFromData)
        self.menu_2.addAction(self.action_baseline_changeBaseline)
        self.menu_2.addAction(self.action_baseline_measureBaseline)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action_configuration)
        self.menu.addAction(self.action_dataPlayBack)
        self.menu.addAction(self.action_offlineDataShow)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LUMIS实时能谱"))
        self.menu.setTitle(_translate("MainWindow", "功能"))
        self.menu_2.setTitle(_translate("MainWindow", "基线设置"))
        self.dockWidget_toolBox.setWindowTitle(_translate("MainWindow", "工具箱"))
        self.groupBox_8.setTitle(_translate("MainWindow", "初始化"))
        self.pushButton_clockSynchronization.setText(_translate("MainWindow", "时钟同步"))
        self.pushButton_reset.setText(_translate("MainWindow", "复位"))
        self.groupBox.setTitle(_translate("MainWindow", "选择配置模式"))
        self.pushButton_config.setText(_translate("MainWindow", "配置"))
        self.groupBox_2.setTitle(_translate("MainWindow", "手动发送命令"))
        self.pushButton_sendCommand.setText(_translate("MainWindow", "发送"))
        self.pushButton_dataReceive.setText(_translate("MainWindow", "开始接收数据"))
        self.groupBox_5.setTitle(_translate("MainWindow", "定时器"))
        self.spinBox_timer_hour.setSuffix(_translate("MainWindow", "小时"))
        self.spinBox_timer_minute.setSuffix(_translate("MainWindow", "分钟"))
        self.checkBox_timer.setText(_translate("MainWindow", "开启定时器"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_linkBehave), _translate("MainWindow", "连接操作"))
        self.groupBox_3.setTitle(_translate("MainWindow", "能谱显示"))
        self.label.setText(_translate("MainWindow", "所在层："))
        self.label_2.setText(_translate("MainWindow", "所选通道："))
        self.label_3.setText(_translate("MainWindow", "基线设置："))
        self.pushButton_singal_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.groupBox_4.setTitle(_translate("MainWindow", "符合能谱"))
        self.label_4.setText(_translate("MainWindow", "所在层："))
        self.label_5.setText(_translate("MainWindow", "显示通道："))
        self.label_6.setText(_translate("MainWindow", "符合通道："))
        self.label_7.setText(_translate("MainWindow", "基线设置："))
        self.pushButton_coincidence_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.groupBox_7.setTitle(_translate("MainWindow", "单层各通道能谱"))
        self.label_8.setText(_translate("MainWindow", "选择层："))
        self.comboBox_oneLayerChannel_tier.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_oneLayerChannel_tier.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_oneLayerChannel_tier.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_oneLayerChannel_tier.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_oneLayerChannel_tier.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_oneLayerChannel_tier.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_oneLayerChannel_tier.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_oneLayerChannel_tier.setItemText(7, _translate("MainWindow", "7"))
        self.pushButton_oneLayerChannel_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "能谱图像"))
        self.groupBox_6.setTitle(_translate("MainWindow", "触发事件"))
        self.label_9.setText(_translate("MainWindow", "触发情况："))
        self.pushButton_triggerCondition_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.label_10.setText(_translate("MainWindow", "XY触发情况："))
        self.pushButton_XYTriggerCondition_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.groupBox_9.setTitle(_translate("MainWindow", "3D成像"))
        self.label_11.setText(_translate("MainWindow", "3D图像："))
        self.pushButton_threeD_addPlot.setText(_translate("MainWindow", "添加图像"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "检测工具"))
        self.groupBox_10.setTitle(_translate("MainWindow", "报警设置"))
        self.checkBox_alarm_messageBox.setText(_translate("MainWindow", "开启弹窗警告"))
        self.pushButton_alarm_clear.setText(_translate("MainWindow", "重置"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_alarm), _translate("MainWindow", "警报功能"))
        self.dockWidget_messageQueue.setWindowTitle(_translate("MainWindow", "消息队列"))
        self.action_baseline_importFromData.setText(_translate("MainWindow", "从数据导入基线"))
        self.action_baseline_changeBaseline.setText(_translate("MainWindow", "修改基线"))
        self.action_configuration.setText(_translate("MainWindow", "仪器配置参数"))
        self.action_baseline_measureBaseline.setText(_translate("MainWindow", "测量基线数据"))
        self.action_dataPlayBack.setText(_translate("MainWindow", "数据回放"))
        self.action_offlineDataShow.setText(_translate("MainWindow", "离线数据显示"))

from pyqtgraph.dockarea import DockArea
