# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\setConfigurtionDailog_basic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 295)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(8)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_exportAsFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_exportAsFile.setObjectName("pushButton_exportAsFile")
        self.horizontalLayout.addWidget(self.pushButton_exportAsFile)
        self.pushButton_sendBinaryOrder = QtWidgets.QPushButton(Dialog)
        self.pushButton_sendBinaryOrder.setObjectName("pushButton_sendBinaryOrder")
        self.horizontalLayout.addWidget(self.pushButton_sendBinaryOrder)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_globalThreshold = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_globalThreshold.setMaximum(1023)
        self.spinBox_globalThreshold.setProperty("value", 280)
        self.spinBox_globalThreshold.setObjectName("spinBox_globalThreshold")
        self.horizontalLayout_2.addWidget(self.spinBox_globalThreshold)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox_globalThreshold = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_globalThreshold.setObjectName("checkBox_globalThreshold")
        self.verticalLayout.addWidget(self.checkBox_globalThreshold)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_globalBais = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_globalBais.setMaximum(255)
        self.spinBox_globalBais.setProperty("value", 141)
        self.spinBox_globalBais.setObjectName("spinBox_globalBais")
        self.horizontalLayout_3.addWidget(self.spinBox_globalBais)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.checkBox_globalBias = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_globalBias.setObjectName("checkBox_globalBias")
        self.verticalLayout_2.addWidget(self.checkBox_globalBias)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.groupBox_triggerMode = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_triggerMode.setObjectName("groupBox_triggerMode")
        self.horizontalLayout_4.addWidget(self.groupBox_triggerMode)
        spacerItem1 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置参数"))
        self.label.setText(_translate("Dialog", "总层数："))
        self.pushButton_exportAsFile.setText(_translate("Dialog", "生成配置文件"))
        self.pushButton_sendBinaryOrder.setText(_translate("Dialog", "发送配置命令"))
        self.groupBox.setTitle(_translate("Dialog", "全局配置（所有层）"))
        self.label_2.setText(_translate("Dialog", "阈值："))
        self.checkBox_globalThreshold.setText(_translate("Dialog", "全局阈值"))
        self.label_3.setText(_translate("Dialog", "偏压："))
        self.checkBox_globalBias.setText(_translate("Dialog", "全局偏压"))
        self.groupBox_triggerMode.setTitle(_translate("Dialog", "符合模式"))

